import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const exportToPDF = ({
  algoA,
  algoB,
  processes,
  metricsA,
  metricsB,
  resultsA,
  resultsB,
}) => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(30, 64, 175); // brand-blue
  doc.text('Schedulix', 14, 20);

  doc.setFontSize(16);
  doc.setTextColor(100);
  doc.text('Algorithm Comparison Report', 14, 30);

  doc.setFontSize(10);
  doc.text(`Exported on: ${timestamp}`, 14, 38);
  doc.line(14, 42, 196, 42);

  // Selected Algorithms
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(`Algorithm A: ${algoA}`, 14, 52);
  doc.text(`Algorithm B: ${algoB}`, 14, 58);

  // Input Process List
  doc.setFontSize(14);
  doc.text('Input Process List', 14, 70);

  const processRows = processes.map(p => [
    p.id,
    p.arrivalTime,
    p.burstTime,
    p.priority
  ]);

  doc.autoTable({
    startY: 75,
    head: [['Process ID', 'Arrival Time', 'Burst Time', 'Priority']],
    body: processRows,
    theme: 'grid',
    headStyles: { fillStyle: [30, 64, 175] }
  });

  // Simulation Results
  const currentY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.text('Simulation Performance Metrics', 14, currentY);

  const getAvg = (results, key) => {
    if (!results || results.length === 0) return 0;
    return results.reduce((acc, r) => acc + (r[key] || 0), 0) / results.length;
  };

  const getUtilization = (m) => ((m.totalTime - (m.idleTime || 0)) / m.totalTime) * 100;
  const getThroughput = (r, m) => r.length / m.totalTime;

  const metricsRows = [
    ['Avg. Waiting Time (ms)', getAvg(resultsA, 'waitingTime').toFixed(2), getAvg(resultsB, 'waitingTime').toFixed(2)],
    ['Avg. Turnaround Time (ms)', getAvg(resultsA, 'turnaroundTime').toFixed(2), getAvg(resultsB, 'turnaroundTime').toFixed(2)],
    ['Avg. Response Time (ms)', getAvg(resultsA, 'responseTime').toFixed(2), getAvg(resultsB, 'responseTime').toFixed(2)],
    ['CPU Utilization (%)', getUtilization(metricsA).toFixed(2), getUtilization(metricsB).toFixed(2)],
    ['Throughput (p/s)', getThroughput(resultsA, metricsA).toFixed(2), getThroughput(resultsB, metricsB).toFixed(2)],
    ['Context Switches', metricsA.contextSwitches || 0, metricsB.contextSwitches || 0],
    ['Total Simulation Time (s)', metricsA.totalTime.toFixed(1), metricsB.totalTime.toFixed(1)]
  ];

  doc.autoTable({
    startY: currentY + 5,
    head: [['Metric', algoA, algoB]],
    body: metricsRows,
    theme: 'striped',
    headStyles: { fillStyle: [30, 64, 175] }
  });

  // Comparison Summary Conclusion
  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.text('Conclusion', 14, finalY);

  const winsA = metricsRows.filter((row, i) => {
      const valA = parseFloat(row[1]);
      const valB = parseFloat(row[2]);
      if (isNaN(valA) || isNaN(valB)) return false;
      const lowerIsBetter = i === 0 || i === 1 || i === 2 || i === 5 || i === 6;
      return lowerIsBetter ? valA < valB : valA > valB;
  }).length;

  const winsB = metricsRows.filter((row, i) => {
      const valA = parseFloat(row[1]);
      const valB = parseFloat(row[2]);
      if (isNaN(valA) || isNaN(valB)) return false;
      const lowerIsBetter = i === 0 || i === 1 || i === 2 || i === 5 || i === 6;
      return lowerIsBetter ? valB < valA : valB > valA;
  }).length;

  let conclusionText = '';
  if (winsA > winsB) conclusionText = `${algoA} performed better overall across most performance metrics.`;
  else if (winsB > winsA) conclusionText = `${algoB} performed better overall across most performance metrics.`;
  else conclusionText = 'Both algorithms showed balanced performance overall.';

  doc.setFontSize(11);
  doc.text(conclusionText, 14, finalY + 8);
  doc.text('This report was generated by Schedulix CPU Scheduling Simulator.', 14, finalY + 16);

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: 'right' });
  }

  doc.save(`Schedulix_Comparison_${algoA}_vs_${algoB}.pdf`);
};
